/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package questionpapergenerator;

import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static questionpapergenerator.add_q.getSelectedButtonText;

/**
 *
 * @author ASUS
 */
public class add_q1 extends javax.swing.JFrame {

    /**
     * Creates new form FormSelect
     */
    public static String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    public add_q1() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/resources/bb.jpg"))));
        initComponents();
        this.setLocationRelativeTo(null);
         Image icx = new ImageIcon(getClass().getResource("/resources/question_mark-icon.jpg")).getImage();
        this.setIconImage(icx);
        this.setTitle("Question Paper Generator");
        try {
UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
SwingUtilities.updateComponentTreeUI(this);
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException exception) {
JOptionPane.showMessageDialog (
this, "Can't change look and feel",
"Invalid PLAF", JOptionPane.ERROR_MESSAGE);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficulty = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbsubname = new javax.swing.JComboBox();
        jcbmarks = new javax.swing.JComboBox();
        jrdEasy = new javax.swing.JRadioButton();
        jrdMed = new javax.swing.JRadioButton();
        jrdHard = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        cmdAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT SUBJECT NAME");

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELECT MARKS");

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SELECT COMPLEXITY LEVEL");

        jLabel7.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD QUESTION");

        jcbsubname.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"java","db","dsa"}));
        jcbsubname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbsubnameItemStateChanged(evt);
            }
        });
        jcbsubname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsubnameActionPerformed(evt);
            }
        });

        jcbmarks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "5" }));

        difficulty.add(jrdEasy);
        jrdEasy.setForeground(new java.awt.Color(255, 255, 255));
        jrdEasy.setText("Easy");
        jrdEasy.setOpaque(false);

        difficulty.add(jrdMed);
        jrdMed.setForeground(new java.awt.Color(255, 255, 255));
        jrdMed.setText("Medium");
        jrdMed.setOpaque(false);
        jrdMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMedActionPerformed(evt);
            }
        });

        difficulty.add(jrdHard);
        jrdHard.setForeground(new java.awt.Color(255, 255, 255));
        jrdHard.setText("Hard");
        jrdHard.setOpaque(false);

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        cmdAdd.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbmarks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrdEasy)
                                        .addGap(54, 54, 54)
                                        .addComponent(jrdMed)
                                        .addGap(41, 41, 41)
                                        .addComponent(jrdHard))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcbsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbsubname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdEasy)
                    .addComponent(jrdMed)
                    .addComponent(jrdHard)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(51, 51, 51)
                .addComponent(cmdAdd)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbsubnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbsubnameItemStateChanged

    }//GEN-LAST:event_jcbsubnameItemStateChanged

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
               try {
            // TODO add your handling code here:
            String subjname=jcbsubname.getSelectedItem().toString();
            String mks=jcbmarks.getSelectedItem().toString();
            String gacc=getSelectedButtonText(difficulty);
            String level="";
            if(gacc.equals("Easy"))
            level="easy";
            else if(gacc.equals("Medium"))
            level="medium";
            else if(gacc.equals("Hard"))
            level="hard";    
            String ques=txtQuestion.getText();
            int a[]=ra(1,3,1);
           int b=a[0];
            String cas = String.valueOf(a[0]);

            //System.out.println(ra(1,3,1));
            //String idd="101";
           try {
                Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            
              java.sql.Connection conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","");
            //  if(subjname.equals("Java"))
             // {
                   if(mks.equals("2"))
                   {
                    if(gacc.equals("Easy"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"e_2`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Medium"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"m_2`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Hard"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"h_2`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                   }
                   
                  if(mks.equals("3"))
                   {
                    if(gacc.equals("Easy"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"e_3`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Medium"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"m_3`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Hard"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"h_3`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                   }
                   if(mks.equals("5"))
                   {
                    if(gacc.equals("Easy"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"e_5`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Medium"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"m_5`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                    if(gacc.equals("Hard"))
                   {
               PreparedStatement stmt = conn.prepareStatement("INSERT INTO `"+subjname+"h_5`(`QUESTION`, `CASE`, `MARK`, `LEVEL`) VALUES (?,?,?,?);");
               stmt.setString(1, ques);
               stmt.setString(2, cas);
               stmt.setString(3, mks);
               stmt.setString(4, level);
               stmt.executeUpdate();
                   }
                   }
                   
             // }
             
              JOptionPane.showMessageDialog(null, "Question added successfully");
              } catch (ClassNotFoundException ex) {
                Logger.getLogger(add_q.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(add_q.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_cmdAddActionPerformed

    private void jcbsubnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsubnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbsubnameActionPerformed

    private void jrdMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        ProjectForm pf = new ProjectForm();
        pf.setVisible(true);

   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.dispose();
        teacher tcn = new teacher();
        tcn.setVisible(true);// TODO add your handling code here:
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new add_q1().setVisible(true);
            }
        });
    }
    int[] ra(int a,int b,int n)
{
ArrayList<Integer> numbers = new ArrayList<Integer>();
     //int b=100;
     //int a=0;
     //int n=6;
     for(int i=a; i<b; i++)
     {
       numbers.add(i+1);
     }
    int[] temp=new int[n];
     Collections.shuffle(numbers);
    // System.out.println(numbers);
     for(int j =0; j < n; j++)
     {
       temp[j]=numbers.get(j);
     }
     return (temp);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.ButtonGroup difficulty;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbmarks;
    private javax.swing.JComboBox jcbsubname;
    private javax.swing.JRadioButton jrdEasy;
    private javax.swing.JRadioButton jrdHard;
    private javax.swing.JRadioButton jrdMed;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
