/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package questionpapergenerator;

import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form FormSelect
     */
    public static String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    public view() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/resources/bb.jpg"))));
        initComponents();
           this.setLocationRelativeTo(null);
         Image icx = new ImageIcon(getClass().getResource("/resources/question_mark-icon.jpg")).getImage();
        this.setIconImage(icx);
        this.setTitle("Question Paper Generator");
        try {
UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
SwingUtilities.updateComponentTreeUI(this);
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException exception) {
JOptionPane.showMessageDialog (
this, "Can't change look and feel",
"Invalid PLAF", JOptionPane.ERROR_MESSAGE);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficulty = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbsubname = new javax.swing.JComboBox();
        jcbmarks = new javax.swing.JComboBox();
        jrdEasy = new javax.swing.JRadioButton();
        jrdMed = new javax.swing.JRadioButton();
        jrdHard = new javax.swing.JRadioButton();
        cmdAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT SUBJECT NAME");

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELECT MARKS");

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SELECT COMPLEXITY LEVEL");

        jcbsubname.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"java","db","dsa"}));
        jcbsubname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbsubnameItemStateChanged(evt);
            }
        });
        jcbsubname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsubnameActionPerformed(evt);
            }
        });

        jcbmarks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "5" }));
        jcbmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmarksActionPerformed(evt);
            }
        });

        difficulty.add(jrdEasy);
        jrdEasy.setForeground(new java.awt.Color(255, 255, 255));
        jrdEasy.setText("Easy");
        jrdEasy.setOpaque(false);

        difficulty.add(jrdMed);
        jrdMed.setForeground(new java.awt.Color(255, 255, 255));
        jrdMed.setText("Medium");
        jrdMed.setOpaque(false);
        jrdMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMedActionPerformed(evt);
            }
        });

        difficulty.add(jrdHard);
        jrdHard.setForeground(new java.awt.Color(255, 255, 255));
        jrdHard.setText("Hard");
        jrdHard.setOpaque(false);

        cmdAdd.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        cmdAdd.setText("View");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(45, 45, 45)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jrdEasy)
                                .addGap(40, 40, 40)
                                .addComponent(jrdMed)
                                .addGap(44, 44, 44)
                                .addComponent(jrdHard))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbsubname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrdEasy)
                    .addComponent(jrdMed, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdHard))
                .addGap(28, 28, 28)
                .addComponent(cmdAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbsubnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbsubnameItemStateChanged

    }//GEN-LAST:event_jcbsubnameItemStateChanged

    private void jcbsubnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsubnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbsubnameActionPerformed

    private void jrdMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdMedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        ProjectForm pf = new ProjectForm();
        pf.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       this.dispose();
        OptionsForm opf = new OptionsForm();
        opf.setVisible(true);
  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcbmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbmarksActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        try {
            // TODO add your handling code here:
            String subjname=jcbsubname.getSelectedItem().toString();
            String mks=jcbmarks.getSelectedItem().toString();
            String gacc=getSelectedButtonText(difficulty);
            String level="";
            if(gacc.equals("Easy"))
            level="easy";
            else if(gacc.equals("Medium"))
            level="medium";
            else if(gacc.equals("Hard"))
            level="hard";
           // int a[]=ra(1,3,1);
            //int b=a[0];
            //String cas = String.valueOf(a[0]);

            try {
                Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection

                java.sql.Connection conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","");
              //  if(subjname.equals("Java"))
               // {
                    if(mks.equals("2"))
                    {
                        if(gacc.equals("Easy"))
                        {
                            PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"e_2`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                            ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                            
                        }
                        if(gacc.equals("Medium"))
                        {
                             PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"m_2`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                            ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                                                    }
                        if(gacc.equals("Hard"))
                        {
                             PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"h_2`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                            ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                            
                        }
                    }

                    if(mks.equals("3"))
                    {
                        if(gacc.equals("Easy"))
                        {
                            PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"e_3`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                           ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                            
                        }
                        if(gacc.equals("Medium"))
                        {
                            PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"m_3`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                          ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                            
                        }
                        if(gacc.equals("Hard"))
                        {
                             PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"h_3`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                        ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                            
                        }
                    }
                    if(mks.equals("5"))
                    {
                        if(gacc.equals("Easy"))
                        { PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"e_5`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                             ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                                                    }
                        if(gacc.equals("Medium"))
                        {
                             PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"m_5`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                            ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                                                    }
                        if(gacc.equals("Hard"))
                        {
                             PreparedStatement stmt = conn.prepareStatement("SELECT `QUESTION`,`MARK`, `LEVEL` FROM `"+subjname+"h_5`;");
                            ResultSet rs=null;
                            rs=stmt.executeQuery();
                                ResultSetTable rtx = new ResultSetTable(rs);
                            jScrollPane2.setViewportView(rtx);
                                                    }
                    }
              //  }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmdAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new view().setVisible(true);
            }
        });
    }
/*int[] ra(int a,int b,int n)
{
ArrayList<Integer> numbers = new ArrayList<Integer>();
     //int b=100;
     //int a=0;
     //int n=6;
     for(int i=a; i<b; i++)
     {
       numbers.add(i+1);
     }
    int[] temp=new int[n];
     Collections.shuffle(numbers);
    // System.out.println(numbers);
     for(int j =0; j < n; j++)
     {
       temp[j]=numbers.get(j);
     }
     return (temp);
}*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.ButtonGroup difficulty;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbmarks;
    private javax.swing.JComboBox jcbsubname;
    private javax.swing.JRadioButton jrdEasy;
    private javax.swing.JRadioButton jrdHard;
    private javax.swing.JRadioButton jrdMed;
    // End of variables declaration//GEN-END:variables
}
